owner: whitney-server
repo: upptime

sites:
  - name: PWS Homepage
    url: https://www.whitney.rip
  - name: Jake Runyan Portfolio
    url: https://jake.runyan.dev
  - name: Jake Runyan Photography
    url: https://jakesphotos.whitney.rip
  - name: PWS Git
    url: https://git.whitney.rip
  - name: PWS Photos
    url: https://images.whitney.rip
  - name: PWS Recipes
    url: https://recipes.whitney.rip
  - name: PWS Grafana
    url: https://grafana.whitney.rip
  - name: Jakes West Coast Site
    url: https://jakeswestcoast.com

status-website:
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  baseUrl: /upptime
  name: PWS Upptime
  introTitle: "PWS Status page is powered by Upptime."
  introMessage: This status page pulls data into the [GitHub repository](https://github.com/whitney-server/upptime).
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub Repo
      href: https://github.com/$OWNER/$REPO
