# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: PWS Homepage
    url: https://www.whitney.rip
  - name: Jake Runyan Portfolio
    url: https://jake.runyan.dev
  - name: Jake Runyan Photography
    url: https://jakesphotos.whitney.rip
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: PWS Upptime
  introTitle: "PWS Status page is powered by Upptime.
  introMessage: This status page pulls data into the [GitHub repository](https://github.com/whitney-server/upptime).
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub Repo
      href: https://github.com/$OWNER/$REPO
